version = 1

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_paths = ["github.com/keptn/keptn/cli", "github.com/keptn/keptn/cli"]
  import_root = "github.com/keptn/keptn"

[[transformers]]
name = "gofmt"
enabled = true
